
export const videoData = [
    // Railway - Maths
    {
      id: 1,
      videoId: "ckHefrcVoSA",
      title: "RRB NTPC Maths Practice Set #01",
      description: "Railway Maths By Rahul Sir.",
      tags: ["Maths", "Railway", "NTPC"],
    },
    {
      id: 2,
      videoId: "DvG6ig5R-r8",
      title: "RRB NTPC Maths Classes 2025",
      description: "Railway Maths By Rahul Sir.",
      tags: ["Maths", "Railway", "NTPC"],
    },
    {
      id: 3,
      videoId: "hVPhrcIm3Uw",
      title: "NTPC Maths Expected Questions 2025",
      description: "Maths expected questions for the upcoming NTPC exam.",
      tags: ["Maths", "Railway", "NTPC"],
    },
    {
      id: 4,
      videoId: "-7r3zQ8LSJM",
      title: "RRB NTPC 2024-25 | How to Manage Time/Study Material",
      description: "Strategy on managing time and study material.",
      tags: ["Strategy", "Railway", "NTPC"],
    },
    {
      id: 5,
      videoId: "gm61r7B5yw0",
      title: "RRB NTPC Maths Marathon Class 2025",
      description: "A marathon session covering key math topics for NTPC.",
      tags: ["Maths", "Railway", "NTPC"],
    },
    {
      id: 6,
      videoId: "70-tTLpD_HU",
      title: "PRACTICE SET 01 || FT. ADITYA RANJAN SIR",
      description: "Practice set for RRB NTPC by Aditya Ranjan Sir.",
      tags: ["Maths", "Railway", "NTPC"],
    },
    {
      id: 7,
      videoId: "pNc14s_4Cz4",
      title: "RRB NTPC Maths Paper Analysis",
      description: "Analysis of the RRB NTPC maths paper.",
      tags: ["Maths", "Railway", "NTPC", "Analysis"],
    },
    {
      id: 8,
      videoId: "OapSkDzmMoM",
      title: "RRB NTPC Maths PYQs by Rahul Sir",
      description: "Previous Year Questions for RRB NTPC Maths.",
      tags: ["Maths", "Railway", "NTPC", "PYQ"],
    },
    // Railway - Reasoning
    {
      id: 9,
      videoId: "U4OKXkbYXSk",
      title: "RRB NTPC Reasoning Practice Set #01",
      description: "Reasoning practice for RRB NTPC.",
      tags: ["Reasoning", "Railway", "NTPC"],
    },
    {
      id: 10,
      videoId: "Kfv27-bwi90",
      title: "RRB NTPC Reasoning Classes 2025",
      description: "Comprehensive reasoning classes for NTPC 2025.",
      tags: ["Reasoning", "Railway", "NTPC"],
    },
    {
      id: 11,
      videoId: "mgQPlaSoMKU",
      title: "RRB NTPC Reasoning Classes 2025 - By Atul Sir",
      description: "Reasoning classes by Atul Sir.",
      tags: ["Reasoning", "Railway", "NTPC"],
    },
    {
      id: 12,
      videoId: "Xlw2zGwkgYQ",
      title: "RRB NTPC Reasoning Paper Analysis",
      description: "Detailed analysis of the reasoning paper.",
      tags: ["Reasoning", "Railway", "NTPC", "Analysis"],
    },
    {
      id: 13,
      videoId: "SJoDTCpE1rY",
      title: "RRB NTPC Reasoning Practice Set #35",
      description: "Practice set for NTPC reasoning.",
      tags: ["Reasoning", "Railway", "NTPC"],
    },
    {
      id: 14,
      videoId: "Y92YfRhCsvA",
      title: "RRB NTPC/Group D Reasoning Practice Set 54",
      description: "Reasoning practice for NTPC and Group D.",
      tags: ["Reasoning", "Railway", "NTPC", "Group D"],
    },
    {
      id: 15,
      videoId: "3EUpEpqbYkE",
      title: "RRB NTPC Reasoning Mock Test 2025 With Solutions",
      description: "A mock test with solutions for reasoning.",
      tags: ["Reasoning", "Railway", "NTPC", "Mock Test"],
    },
    {
      id: 16,
      videoId: "TuFeRWS1xoU",
      title: "RRB NTPC Reasoning Sample Paper",
      description: "Sample paper for NTPC reasoning section.",
      tags: ["Reasoning", "Railway", "NTPC"],
    },
    {
      id: 17,
      videoId: "KT0fC_pH3ug",
      title: "RRB NTPC Reasoning Practice Set #01",
      description: "Another practice set for NTPC reasoning.",
      tags: ["Reasoning", "Railway", "NTPC"],
    },
    {
      id: 18,
      videoId: "k2z25kUqvaw",
      title: "RRB NTPC Reasoning Classes 2025",
      description: "Reasoning classes for the 2025 NTPC exam.",
      tags: ["Reasoning", "Railway", "NTPC"],
    },
    // Railway - General Awareness
    {
      id: 19,
      videoId: "rDcY-n6hS6Q",
      title: "General awareness expected questions for RRB NTPC|rrb group D",
      description: "Expected GA questions for NTPC and Group D.",
      tags: ["GA", "Railway", "NTPC", "Group D"],
    },
    {
      id: 20,
      videoId: "gqQadT5N_kE",
      title: "RRB NTPC GENERAL AWARENESS ENGLISH IMPORTANT",
      description: "Important GA topics in English.",
      tags: ["GA", "Railway", "NTPC"],
    },
    {
      id: 21,
      videoId: "btUGhT0AAM0",
      title: "General awareness for rrb ntpc & Group D",
      description: "GA for NTPC and Group D aspirants.",
      tags: ["GA", "Railway", "NTPC", "Group D"],
    },
    {
      id: 22,
      videoId: "ZYoezaocAM0",
      title: "RRB NTPC GENERAL AWARENESS PRACTICE QUESTIONS SET 1",
      description: "Practice questions for General Awareness.",
      tags: ["GA", "Railway", "NTPC"],
    },
    {
      id: 23,
      videoId: "cgUaSSsvPdQ",
      title: "Most Important Study Material for RRB NTPC Exam 2025",
      description: "A guide to the most important study materials.",
      tags: ["Strategy", "Railway", "NTPC"],
    },
    {
      id: 24,
      videoId: "cfixCjBaR58",
      title: "Expected Questions For RRB NTPC Exams PART-6",
      description: "A set of expected questions for the exam.",
      tags: ["GA", "Railway", "NTPC"],
    },
    {
      id: 25,
      videoId: "mpnsJOnAJr0",
      title: "DSSSB KVS NVS SSC NTPC | GK & CA ka Daily Dose",
      description: "Daily dose of GK and Current Affairs.",
      tags: ["GA", "Current Affairs", "Railway"],
    },
    {
      id: 26,
      videoId: "6Ej7oFl4BNQ",
      title: "GK & CA Daily Dose on Mentors 36 - CTET KVS DSSSB NVS SSC",
      description: "Another daily dose of GK and Current Affairs.",
      tags: ["GA", "Current Affairs", "Railway"],
    },
    {
      id: 27,
      videoId: "YqGbTTn7yTs",
      title: "Top GK & Current Affairs 16 Sept 2019 With MCQ",
      description: "GK & CA from September 2019.",
      tags: ["GA", "Current Affairs", "Railway"],
    },
    {
      id: 28,
      videoId: "zemRLmTQ888",
      title: "Top GK & Current Affairs 13 Sept 2019 With MCQ",
      description: "GK & CA from September 2019.",
      tags: ["GA", "Current Affairs", "Railway"],
    },
    // Railway - General Science
    {
      id: 29,
      videoId: "rYxEc-0-q2g",
      title: "General Science For RRB ALP/Tech/RPF SI | Day 01 | Protyush Sir",
      description: "General Science class by Protyush Sir.",
      tags: ["General Science", "Railway", "ALP"],
    },
    {
      id: 30,
      videoId: "FI_YI3Dipfk",
      title: "RRB NTPC GS Classes 2025",
      description: "General Science classes for NTPC 2025.",
      tags: ["General Science", "Railway", "NTPC"],
    },
    {
      id: 31,
      videoId: "VlOZesmi05M",
      title: "ATOMIC STRUCTURE - D, ALP, TECHNICIAN & SSC EXAMS",
      description: "A class on Atomic Structure.",
      tags: ["General Science", "Physics", "Railway"],
    },
    {
      id: 32,
      videoId: "PLmCUvWMDFybvpZXg5bJtm3wUSNFp0GxkU",
      title: "RRB NTPC GENERAL SCIENCE (Playlist)",
      description: "A playlist of General Science videos for NTPC.",
      tags: ["General Science", "Railway", "NTPC", "Playlist"],
    },
    {
      id: 33,
      videoId: "PL0Nb4Te42yLkvVpO7Ltuvmzblnj6aPtF6",
      title: "General Science - Physics - Most Important mcqs in English (Playlist)",
      description: "Important Physics MCQs playlist.",
      tags: ["General Science", "Physics", "Railway", "Playlist"],
    },
    {
      id: 34,
      videoId: "fREEoMTDegI",
      title: "Last 3 Years General Science Questions asked in RRB NTPC / ALP",
      description: "Previous years' questions from General Science.",
      tags: ["General Science", "Railway", "NTPC", "PYQ"],
    },
    {
      id: 35,
      videoId: "pshLoU8QmoI",
      title: "RRB NTPC 2024 | By Protyush Sir",
      description: "General Science class by Protyush Sir.",
      tags: ["General Science", "Railway", "NTPC"],
    },
    {
      id: 36,
      videoId: "MlL2YgvcvmQ",
      title: "Class-1 General Science Questions and Answers in English for",
      description: "Q&A session for General Science.",
      tags: ["General Science", "Railway"],
    },
    {
      id: 37,
      videoId: "U76aA_RSuIs",
      title: "RRB NTPC GENERAL SCIENCE CLASSES IN ENGLISH",
      description: "General Science classes in English.",
      tags: ["General Science", "Railway", "NTPC"],
    },
    {
      id: 38,
      videoId: "hVEWrohEBJY",
      title: "Class- 3 General Science Questions and Answers in English for",
      description: "Another Q&A session for General Science.",
      tags: ["General Science", "Railway"],
    },
    // Railway - Strategy
    {
      id: 39,
      videoId: "S3XDxoDcLMI",
      title: "Complete Roadmap with Do's & Don'ts | NTPC Strategy by Sahil Sir",
      description: "A complete roadmap and strategy.",
      tags: ["Strategy", "Railway", "NTPC"],
    },
    {
      id: 40,
      videoId: "qnpEgmXkTM8",
      title: "The BEST RRB NTPC Preparation Strategy",
      description: "A guide to the best preparation strategy.",
      tags: ["Strategy", "Railway", "NTPC"],
    },
    {
      id: 41,
      videoId: "hewmHiOh-oQ",
      title: "How I Scored 98/120 in RRB NTPC CBT-2",
      description: "A topper's strategy and experience.",
      tags: ["Strategy", "Railway", "NTPC"],
    },
    {
      id: 42,
      videoId: "s5p-xA-KpvY",
      title: "SHORT CUTS & TRICKS TO EASILY FIND RANKING & ORDERING",
      description: "Tricks for ranking and ordering questions.",
      tags: ["Reasoning", "Tricks", "Railway"],
    },
    {
      id: 43,
      videoId: "Y4QSPD_Dv04",
      title: "RRB NTPC 2025 CBT 1 Preparation Strategy | Crack in First Attempt",
      description: "How to crack the exam in the first attempt.",
      tags: ["Strategy", "Railway", "NTPC"],
    },
    {
      id: 44,
      videoId: "nzjnwOYPyXk",
      title: "How to Crack Railway Exams in First Attempt",
      description: "General strategy for cracking railway exams.",
      tags: ["Strategy", "Railway"],
    },
    {
      id: 45,
      videoId: "TChvEOGhxDM",
      title: "How to Prepare GS for RRB NTPC in English Medium?",
      description: "Strategy for General Science preparation in English.",
      tags: ["Strategy", "General Science", "Railway", "NTPC"],
    },
    {
      id: 46,
      videoId: "LL65rmf-hYI",
      title: "How to Complete RRB NTPC Syllabus 2025 in 3 Months",
      description: "A 3-month preparation plan.",
      tags: ["Strategy", "Railway", "NTPC"],
    },
    {
      id: 47,
      videoId: "hDbmwnGr4b8",
      title: "RAILWAY Exams || Ideas and Strategy to clear",
      description: "Ideas and strategies for railway exams.",
      tags: ["Strategy", "Railway"],
    },
    {
      id: 48,
      videoId: "U0KBarh9ae8",
      title: "RRB NTPC 2025 Complete Blueprint & Detailed Strategy",
      description: "A complete blueprint and detailed strategy.",
      tags: ["Strategy", "Railway", "NTPC"],
    },
    // Railway - Group D
    {
      id: 49,
      videoId: "nJYKL-S-cxs",
      title: "GROUP D तैयारी शुरू करें 1 LAKH POST",
      description: "Preparation guide for Group D posts.",
      tags: ["Strategy", "Railway", "Group D"],
    },
    // Bank - Quant
    {
      id: 50,
      videoId: "JYTRM0G5YFM",
      title: "IBPS RRB PO/Clerk 2025 | Quantitative Aptitude Practice",
      description: "Quant practice for IBPS RRB PO/Clerk.",
      tags: ["Maths", "Bank", "IBPS"],
    },
    {
      id: 51,
      videoId: "RVvbiQmW_dg",
      title: "How To Attempt Exam Paper | SBI & IBPS PO 2025 Quant Preparation",
      description: "Strategy for attempting the quant section in bank exams.",
      tags: ["Strategy", "Maths", "Bank", "SBI", "IBPS"],
    },
    {
      id: 52,
      videoId: "IQZW0xeZoHM",
      title: "IBPS PO Prelims 2025 | Quantitative Aptitude | Mock Paper",
      description: "A mock paper for IBPS PO prelims quant.",
      tags: ["Maths", "Bank", "IBPS", "Mock Test"],
    },
    {
      id: 53,
      videoId: "rv0fNbYva8I",
      title: "SBI PO Quantitative Aptitude 2025 | SBI PO 7 Days 7 Paper",
      description: "A 7-day paper series for SBI PO quant.",
      tags: ["Maths", "Bank", "SBI"],
    },
    {
      id: 54,
      videoId: "7W7uQcHvdnU",
      title: "English Vs Aptitude for Bank Exams | Important Questions",
      description: "Comparison and important questions for English and Aptitude.",
      tags: ["Strategy", "Bank"],
    },
    {
      id: 55,
      videoId: "Iy0_Zf4MJbA",
      title: "5 Tips for Quantitative Aptitude [BANK EXAM QUANT for SBI PO]",
      description: "5 essential tips for quant preparation.",
      tags: ["Strategy", "Maths", "Bank", "SBI"],
    },
    {
      id: 56,
      videoId: "6EaVm8Ob4l8",
      title: "Bank exam Preparation for beginners in 2025 | English",
      description: "Preparation guide for beginners.",
      tags: ["Strategy", "Bank"],
    },
    {
      id: 57,
      videoId: "npH9zb1tQ08",
      title: "IBPS PO Reasoning, English & Quant Marathon",
      description: "A marathon session covering all three subjects.",
      tags: ["Maths", "Reasoning", "English", "Bank", "IBPS"],
    },
    {
      id: 58,
      videoId: "aPHyU9dLF8Q",
      title: "IBPS RRB PO 2025 | Strategy to Increase Marks in Quants",
      description: "Strategy to improve your quant score.",
      tags: ["Strategy", "Maths", "Bank", "IBPS"],
    },
    {
      id: 59,
      videoId: "MvqtUAdYKHk",
      title: "Easiest Quant Strategy BY SBI PO Ameesha Yadav",
      description: "A topper's quant strategy.",
      tags: ["Strategy", "Maths", "Bank", "SBI"],
    },
    // Bank - Reasoning
    {
      id: 60,
      videoId: "N3qaU-xtrbY",
      title: "SBI PO 2025 English, Quant, Reasoning Marathon Class",
      description: "Marathon class for SBI PO.",
      tags: ["Reasoning", "Maths", "English", "Bank", "SBI"],
    },
    {
      id: 61,
      videoId: "6EaVm8Ob4l8",
      title: "Bank exam Preparation for beginners in 2025 | English",
      description: "Guide for beginners focusing on bank exams.",
      tags: ["Strategy", "Bank"],
    },
    {
      id: 62,
      videoId: "GPYnr21CNao",
      title: "IBPS PO Reasoning, English & Quant Marathon",
      description: "Marathon session for IBPS PO.",
      tags: ["Reasoning", "English", "Maths", "Bank", "IBPS"],
    },
    {
      id: 63,
      videoId: "Tu78K1CIEf4",
      title: "SBI PO & IBPS PO 2025 Reasoning | TOP 75 Reasoning Questions",
      description: "Top 75 reasoning questions.",
      tags: ["Reasoning", "Bank", "SBI", "IBPS"],
    },
    {
      id: 64,
      videoId: "_Rbx0LEsPHs",
      title: "IBPS PO & SBI PO 2025 | Complete Reasoning Paper",
      description: "A complete reasoning paper for practice.",
      tags: ["Reasoning", "Bank", "SBI", "IBPS"],
    },
    {
      id: 65,
      videoId: "ZT6J4wcwols",
      title: "SBI PO Reasoning 45 Days Crash Course #5",
      description: "A crash course for SBI PO reasoning.",
      tags: ["Reasoning", "Bank", "SBI"],
    },
    {
      id: 66,
      videoId: "oJTyEiCU3AY",
      title: "IBPS PO English Expected Paper | by Rupam Ma'am #1",
      description: "Expected English paper for IBPS PO.",
      tags: ["English", "Bank", "IBPS"],
    },
    {
      id: 67,
      videoId: "cou2xjqZjS0",
      title: "IBPS RRB PO & Clerk 2025 | Reasoning Super Mock-2",
      description: "A super mock for IBPS RRB reasoning.",
      tags: ["Reasoning", "Bank", "IBPS", "Mock Test"],
    },
    {
      id: 68,
      videoId: "32Xw5CCBVW4",
      title: "IBPS RRB PO Mains 2025 | English Mock Test with Solutions | Varun",
      description: "English mock test for mains.",
      tags: ["English", "Bank", "IBPS", "Mock Test"],
    },
    {
      id: 69,
      videoId: "npH9zb1tQ08",
      title: "IBPS PO Reasoning, English & Quant Marathon",
      description: "Another marathon session.",
      tags: ["Reasoning", "English", "Maths", "Bank", "IBPS"],
    },
    // Bank - English
    {
      id: 70,
      videoId: "EZMFr5oxLXU",
      title: "Complete English Strategy for All Bank Exams 2025 | Nimisha Bansal",
      description: "A complete English strategy by Nimisha Bansal.",
      tags: ["English", "Strategy", "Bank"],
    },
    {
      id: 71,
      videoId: "FvU75d9oVXc",
      title: "How to Prepare English From Basic for Bank Exams 2026",
      description: "A guide for preparing English from scratch.",
      tags: ["English", "Strategy", "Bank"],
    },
    {
      id: 72,
      videoId: "pqL7j1vN9Is",
      title: "How to Prepare Pre & Mains English | Varun Chitra Sir",
      description: "Preparation strategy for both pre and mains.",
      tags: ["English", "Strategy", "Bank"],
    },
    {
      id: 73,
      videoId: "eMHp9AdirdA",
      title: "IBPS PO 50 DAYS ENGLISH PREPARATION & STUDY PLAN",
      description: "A 50-day study plan for English.",
      tags: ["English", "Strategy", "Bank", "IBPS"],
    },
    {
      id: 74,
      videoId: "CM_Lt_1zxtU",
      title: "Complete English Preparation (for serious aspirants only)",
      description: "An in-depth English preparation guide.",
      tags: ["English", "Strategy", "Bank"],
    },
    {
      id: 75,
      videoId: "PLmrfuXtxLLHN5R1JprKmvacY_7RftGxXy",
      title: "Complete Course on English for BANK/SSC/CDS (Basic to Advance) (Playlist)",
      description: "A complete course playlist for English.",
      tags: ["English", "Bank", "Playlist"],
    },
    {
      id: 76,
      videoId: "tdX8c_SxfJU",
      title: "SBI PO English Most Asked Questions | English by Anchal Ma'am",
      description: "Most frequently asked questions in SBI PO.",
      tags: ["English", "Bank", "SBI"],
    },
    {
      id: 77,
      videoId: "3i0gusNx7Vk",
      title: "Bank Exam 2026 | Episode 5 | English Preparation for IBPS Clerk",
      description: "English preparation for IBPS Clerk.",
      tags: ["English", "Bank", "IBPS"],
    },
    {
      id: 78,
      videoId: "g3BU_xnM1AI",
      title: "Complete English Preparation | All Bank & Insurance Exams | Varun",
      description: "Complete English prep for bank and insurance exams.",
      tags: ["English", "Bank", "Insurance"],
    },
    {
      id: 79,
      videoId: "dFVabODv410",
      title: "IBPS PO Pre 2025 English Mock Test",
      description: "Mock test for IBPS PO prelims English.",
      tags: ["English", "Bank", "IBPS", "Mock Test"],
    },
];
