
import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        body: ['var(--font-body)', 'sans-serif'],
        headline: ['var(--font-headline)', 'sans-serif'],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        // New theme colors
        deep_twilight: {
          DEFAULT: '#03045e',
          100: '#010113',
          200: '#010226',
          300: '#020338',
          400: '#02044b',
          500: '#03045e',
          600: '#0508ae',
          700: '#0f12f8',
          800: '#5f61fa',
          900: '#afb0fd',
        },
        french_blue: {
          DEFAULT: '#023e8a',
          100: '#000c1b',
          200: '#011836',
          300: '#012451',
          400: '#02306d',
          500: '#023e8a',
          600: '#035cd1',
          700: '#2381fc',
          800: '#6cabfd',
          900: '#b6d5fe',
        },
        bright_teal_blue: {
          DEFAULT: '#0077b6',
          100: '#001825',
          200: '#003049',
          300: '#00486e',
          400: '#005f93',
          500: '#0077b6',
          600: '#00a2f9',
          700: '#3bbaff',
          800: '#7cd1ff',
          900: '#bee8ff',
        },
        blue_green: {
          DEFAULT: '#0096c7',
          100: '#001e28',
          200: '#003c50',
          300: '#005a77',
          400: '#00779f',
          500: '#0096c7',
          600: '#06c1ff',
          700: '#44d0ff',
          800: '#83e0ff',
          900: '#c1efff',
        },
        turquoise_surf: {
          DEFAULT: '#00b4d8',
          100: '#00242b',
          200: '#004756',
          300: '#006b81',
          400: '#008fab',
          500: '#00b4d8',
          600: '#12d8ff',
          700: '#4ee1ff',
          800: '#89ebff',
          900: '#c4f5ff',
        },
        sky_aqua: {
          DEFAULT: '#48cae4',
          100: '#082d34',
          200: '#105a69',
          300: '#17879d',
          400: '#1fb4d1',
          500: '#48cae4',
          600: '#6dd5e9',
          700: '#92dfef',
          800: '#b6eaf4',
          900: '#dbf4fa',
        },
        frosted_blue: {
          DEFAULT: '#ade8f4',
          100: '#0a3f4a',
          200: '#147e93',
          300: '#1ebddd',
          400: '#65d4ea',
          500: '#ade8f4',
          600: '#beedf6',
          700: '#cff1f8',
          800: '#dff6fb',
          900: '#effafd',
        },
        light_cyan: {
          DEFAULT: '#caf0f8',
          100: '#0a444f',
          200: '#15889f',
          300: '#2ac4e3',
          400: '#79daee',
          500: '#caf0f8',
          600: '#d4f3f9',
          700: '#dff6fb',
          800: '#e9f9fc',
          900: '#f4fcfe',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
         'pulse-fast': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.5' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'pulse-fast': 'pulse-fast 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
